# Generated by Django 3.2.8 on 2021-10-07 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('alt', models.CharField(blank=True, max_length=50)),
                ('new_price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('Width', models.CharField(max_length=50)),
                ('Height', models.CharField(max_length=50)),
                ('Depth', models.CharField(max_length=50)),
                ('Weight', models.CharField(max_length=50)),
                ('metatitle', models.CharField(blank=True, max_length=100, null=True)),
                ('metadesc', models.CharField(blank=True, max_length=250, null=True)),
                ('Category', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
