# Generated by Django 3.2.8 on 2021-10-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Phone',
            field=models.CharField(max_length=15),
        ),
    ]
