# Generated by Django 3.2.8 on 2021-10-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_address_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Address_Line_1', models.CharField(max_length=500)),
                ('Address_Line_2', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
            ],
        ),
    ]
